trigger:
- master

jobs:
- job: linux
  displayName: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    fetchDepth: 1
  - template: config/azure/azure-gradle-step.yml

- job: mac
  displayName: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - checkout: self
    fetchDepth: 1
  - template: config/azure/azure-gradle-step.yml

- job: windows
  displayName: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
    fetchDepth: 1
  - template: config/azure/azure-gradle-step.yml
